### ISSUE TITLE
[HELP] Not show errors

### ISSUE THREAD

**Issue by max10rogerio** [whitecolor/ts-node-dev#121]
When I run the command: `nodemon --ext ts,gql --exec node -r ts-node/register  src/server.ts`
This show me an error:
```console
yarn run v1.19.1
$ nodemon --ext ts,gql --exec node -r ts-node/register  src/server.ts
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src\**\*
[nodemon] watching extensions: ts,gql
[nodemon] starting `node -r ts-node/register src/server.ts`

C:\Projetos\deltaweb-server\node_modules\ts-node\src\index.ts:421
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/server.ts:26:7 - error TS2322: Type 'string[]' is not assignable to type 'number'.

26 const t:number = ["a"]
         ~

    at createTSError (C:\Projetos\deltaweb-server\node_modules\ts-node\src\index.ts:421:12)
    at reportTSError (C:\Projetos\deltaweb-server\node_modules\ts-node\src\index.ts:425:19)
    at getOutput (C:\Projetos\deltaweb-server\node_modules\ts-node\src\index.ts:530:36)
    at Object.compile (C:\Projetos\deltaweb-server\node_modules\ts-node\src\index.ts:735:32)
    at Module.m._compile (C:\Projetos\deltaweb-server\node_modules\ts-node\src\index.ts:814:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Projetos\deltaweb-server\node_modules\ts-node\src\index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[nodemon] app crashed - waiting for file changes before starting...

```

But when I run the command: `ts-node-dev ./src/server.ts`, the application initializes with errors!
Why? How to configure for when there are errors in the code, the server stops?
```console
yarn run v1.19.1
$ C:\Projetos\deltaweb-server\node_modules\.bin\ts-node-dev ./src/server.ts
Using ts-node version 8.6.2, typescript version 3.7.5
Running in development mode
Server ready at http://localhost:4000/graphql
Subscriptions ready at ws://localhost:4000/graphql
```

**Comment by max10rogerio** [comment]
https://github.com/whitecolor/ts-node-dev/issues/119#issuecomment-581311690
