### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by kanjieater** [whitecolor/ts-node-dev#127]
Trying to narrow down why I'm seeing this error:
```
Error: write EPIPE
    at process.target._send (internal/child_process.js:812:20)
    at process.target.send (internal/child_process.js:683:19)
    at Object.exports.send (/Users/x/IdeaProjects/asdf/node_modules/ts-node-dev/lib/ipc.js:14:23)
    at /Users/x/IdeaProjects/asdf/node_modules/ts-node-dev/lib/wrap.js:61:7
    at Object.nodeDevHook [as .js] (/Users/x/IdeaProjects/asdf/node_modules/ts-node-dev/lib/hook.js:58:27)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/x/IdeaProjects/asdf/node_modules/micromatch/lib/compilers.js:4:15)
Child got SIGTERM, exiting.
```

It seems like it is coming directly from ts-node-dev.

**Comment by Tsourdox** [comment]
In my case I had a running instance in the background - killed my node processes and the error went away. Hope it helps!

**Comment by matiaschileno** [comment]
I have the same issue when application is already restarting and a file is modified at the same time.

**Comment by michaelfarrell76** [comment]
any idea on how to fix this? i think @matiaschileno is right about how this happens

**Comment by whitecolor** [comment]
I couldn't reproduce this in tests. You may try to add [test](https://github.com/whitecolor/ts-node-dev/blob/master/test/index.ts#L39) that reproduce the issue.

**Comment by endel** [comment]
I just experienced this as well, and I think it's the same scenario as @matiaschileno

**Comment by theoephraim** [comment]
+1 encountering this due to saving files multiple times while app is still restarting

**Comment by jameskennethrobinson** [comment]
+1

**Comment by SebTVisage** [comment]
I can also reproduce this if the node process crashed and a file changed.

Basically I'm testing uncaught promises in my app. When it happens, node crashes, but ts-node-dev does not report it. And if I edit a file, I have the EPIPE error in an infinite loop.
