### ISSUE TITLE
Compatibility with tsconfig-paths

### ISSUE THREAD

**Issue by thisdotvoid** [whitecolor/ts-node-dev#13]
running `ts-node-dev -r tsconfig-paths/register src/index.ts` gives:
```
./node_modules/resolve/lib/sync.js:19
        throw new TypeError('Path must be a string.');
        ^

TypeError: Path must be a string.
    at module.exports (/Volumes/Extended/Home/Code/mojvix-server/node_modules/resolve/lib/sync.js:19:15)
    at module.exports (/Volumes/Extended/Home/Code/mojvix-server/node_modules/ts-node-dev/lib/resolveMain.js:15:14)
    at Object.<anonymous> (/Volumes/Extended/Home/Code/mojvix-server/node_modules/ts-node-dev/lib/wrap.js:13:12)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at Function.Module._preloadModules (module.js:725:12)
```
`ts-node -r tsconfig-paths/register src/index.ts` works fine. what could be a problem?

**Comment by whitecolor** [comment]
Thanks for notice, should be fixed.

**Comment by thisdotvoid** [comment]
@whitecolor  I fixed it by manually requiring `tsconfig-paths/register` in index, but it is 2x slower than `nodemon ts-node` combination, any thoughts on that?

**Comment by whitecolor** [comment]
You mean slower at first start, or at any restart? Do you have a big project?

**Comment by thisdotvoid** [comment]
Not sure what could be qualified as a big project. Hapi web server with GraphQL.
Start time and subsequent restarts are the same, ~10 sec. with ts-node ~6 sec. Here is my tsconfig:
```json
{
  "compilerOptions": {
    "target": "es2017",
    "lib": [
      "dom", "esnext"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./dist",
    "rootDir": "./",
    "alwaysStrict": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "baseUrl": "./",
    "paths": {
      "@app/error": [
        "src/server/errors"
      ],
      "@app/entity": [
        "src/entity"
      ],
      "@app/repository": [
        "src/repository"
      ],
      "@app/service": [
        "src/service"
      ]
    }
  },
  "include": [
    "./**/*.ts"
  ],
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```

**Comment by whitecolor** [comment]
Can you test on just one file for the same project? Just create some test.ts without imports, and compare times.

**Comment by thisdotvoid** [comment]
So, after some testing, it looks like most of the time is taken by just importing dependencies, I guess it can't be optimized with this project?

**Comment by whitecolor** [comment]
> Docker issue is solved, now timing for both methods look the same.

What was the problem? Time is the same for your project, or one file?

**Comment by thisdotvoid** [comment]
It's a known problem that docker volumes have poor performance on macOS, that was the reason why imports took a lot of time. "fixing" it just means setting `cached` flag on volume, it improves performance, but still it's a little bit slower than host.

Testing on a linux machine, times are roughly the same, ~1sec for full project. Although it is hard to say, `ts-node-dev` seems ~100ms faster, I'm not sure how to measure it that precisely.

**Comment by whitecolor** [comment]
Hm anyway it should be much faster on restarts as it doesn't reinit compilation process and uses shared one.

**Comment by coler-j** [comment]
@whitecolor can you doublecheck (or point to previous work where you fixed this) as the lib appears to not be working with `tsconfig-paths` again.
