### ISSUE TITLE
Running ts-node-dev at two projects at the same time crashes

### ISSUE THREAD

**Issue by danielpa9708** [whitecolor/ts-node-dev#14]
After launching the second time `ts-node-dev`, the first one throws this error:

```
/home/user/.local/lib/node_modules/ts-node-dev/lib/index.js:81
        var split = data.split('\n')
                         ^
TypeError: Cannot read property 'split' of undefined
    at ReadFileContext.callback (/home/user/.local/lib/node_modules/ts-node-dev/lib/index.js:81:26)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by whitecolor** [comment]
In the same dir?

**Comment by danielpa9708** [comment]
Start one, leave it running, start the other, then crashes the first one.
I'll try the latest version, thanks

**Comment by danielpa9708** [comment]
no luck, I tried with `ts-node-dev@1.0.0-pre.22`, and the first one still crashed,

this is the error:
```
Error reading compile request file { Error: ENOENT: no such file or directory, open '/tmp/.ts-node/compiled/12264977755469597.req'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/tmp/.ts-node/compiled/12264977755469597.req' }
```
sorry I didn't post it before

**Comment by whitecolor** [comment]
Well, can not reproduce it, I can start simultaneously two tasks, no error. Do your project has some intersections?

Btw the error `Error reading compile request file` above should not stop the process.
