### ISSUE TITLE
Throws error every time Prettier reformats file on IntellIj via FileWatcher

### ISSUE THREAD

**Issue by stephanoparaskeva** [whitecolor/ts-node-dev#148]
If I change a file. Press save. The file will be reformatted via prettier and filewatcher (which is the main filewatcher for intellij) but ts-node-dev throws this error every time: 
```21:58 Restarting: /Users/Stephano/Development/code/head/archimedes/index.ts has been modified
Error: write EPIPE
    at process.target._send (internal/child_process.js:835:20)
    at process.target.send (internal/child_process.js:706:19)
    at Object.exports.send (/Users/Stephano/Development/code/head/archimedes/node_modules/ts-node-dev/lib/ipc.js:14:23)
    at /Users/Stephano/Development/code/head/archimedes/node_modules/ts-node-dev/lib/wrap.js:61:7
    at Object.nodeDevHook [as .js] (/Users/Stephano/Development/code/head/archimedes/node_modules/ts-node-dev/lib/hook.js:58:27)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/Stephano/Development/code/head/archimedes/src/index.ts:31:1)
Using ts-node version 8.10.2, typescript version 3.9.3
```

Latset version for everything.

**Comment by whitecolor** [comment]
Check if happens with the latest, as watcher has been replaced.

**Comment by michaelfarrell76** [comment]
would this be in `1.0.0-pre.48` ?

**Comment by VottusCode** [comment]
The same happens to me anytime files get edited as well.
```ts
[w:graphql] Error: write EPIPE
[w:graphql]     at process.target._send (internal/child_process.js:832:20)
[w:graphql]     at process.target.send (internal/child_process.js:703:19)
[w:graphql]     at Object.exports.send (/home/mia/Desktop/teyvatdev-api/node_modules/ts-node-dev/lib/ipc.js:14:23)
[w:graphql]     at /home/mia/Desktop/teyvatdev-api/node_modules/ts-node-dev/lib/wrap.js:62:7
[w:graphql]     at Object.nodeDevHook [as .js] (/home/mia/Desktop/teyvatdev-api/node_modules/ts-node-dev/lib/hook.js:58:27)
[w:graphql]     at Module.load (internal/modules/cjs/loader.js:928:32)
[w:graphql]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[w:graphql]     at Module.require (internal/modules/cjs/loader.js:952:19)
[w:graphql]     at require (internal/modules/cjs/helpers.js:88:18)
[w:graphql]     at Object.<anonymous> (/home/mia/Desktop/prfldr/packages/core/src/entities/smentity/index.ts:2:1)
```

**Comment by VottusCode** [comment]
The same happens to me anytime files get edited as well.
```ts
[w:graphql] Error: write EPIPE
[w:graphql]     at process.target._send (internal/child_process.js:832:20)
[w:graphql]     at process.target.send (internal/child_process.js:703:19)
[w:graphql]     at Object.exports.send (/home/mia/Desktop/prfldr/node_modules/ts-node-dev/lib/ipc.js:14:23)
[w:graphql]     at /home/mia/Desktop/prfldr/node_modules/ts-node-dev/lib/wrap.js:62:7
[w:graphql]     at Object.nodeDevHook [as .js] (/home/mia/Desktop/prfldr/node_modules/ts-node-dev/lib/hook.js:58:27)
[w:graphql]     at Module.load (internal/modules/cjs/loader.js:928:32)
[w:graphql]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[w:graphql]     at Module.require (internal/modules/cjs/loader.js:952:19)
[w:graphql]     at require (internal/modules/cjs/helpers.js:88:18)
[w:graphql]     at Object.<anonymous> (/home/mia/Desktop/prfldr/packages/core/src/entities/smentity/index.ts:2:1)
```

**Comment by elgambet** [comment]
This is happening to me also, but only if I edit multiple times in a short period of time.

Error: write EPIPE,
    at process.target._send (internal/child_process.js:806:20),
    at process.target.send (internal/child_process.js:677:19),
    at Object.exports.send (node_modules/ts-node-dev/lib/ipc.js:17:14),
    at node_modules/ts-node-dev/lib/wrap.js:88:9,
    at Object.nodeDevHook [as .js] (node_modules/ts-node-dev/lib/hook.js:61:17),
         at Module.load (internal/modules/cjs/loader.js:985:32),
         at Function.Module._load (internal/modules/cjs/loader.js:878:14),
         at Module.require (internal/modules/cjs/loader.js:1025:19),
         at require (internal/modules/cjs/helpers.js:72:18),
         at Object.<anonymous> (node_modules/mongoose/lib/index.js:15:3)

**Comment by deividr** [comment]
Any idea how to solve this?
