### ISSUE TITLE
"throw null" causes a crash

### ISSUE THREAD

**Issue by nathanfranke** [whitecolor/ts-node-dev#157]
```ts
export class MyClass {
	static get(): MyClass {
		throw null;
	}
}

let myClass: MyClass = MyClass.get();
```

```
$ yarn ts-node-dev bug.ts
yarn run v1.22.4
$ /home/nathanfranke/workspace/Test/node_modules/.bin/ts-node-dev bug.ts
Using ts-node version 8.10.2, typescript version 3.9.5
/home/nathanfranke/workspace/Test/node_modules/ts-node-dev/lib/wrap.js:48
  var isTsError = err.message && /TypeScript/.test(err.message)
                      ^

TypeError: Cannot read property 'message' of null
    at process.<anonymous> (/home/nathanfranke/workspace/Test/node_modules/ts-node-dev/lib/wrap.js:48:23)
    at process.emit (events.js:315:20)
    at process.emit (/home/nathanfranke/workspace/Test/node_modules/source-map-support/source-map-support.js:495:21)
    at process._fatalException (internal/process/execution.js:169:25)
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by whitecolor** [comment]
Thanks will fix this.
