### ISSUE TITLE
Compiler crashes for JS files and ES modules

### ISSUE THREAD

**Issue by fhessenberger** [whitecolor/ts-node-dev#158]
Since version `1.0.0-pre.45` the `allowJs` flag doesn't seem to get picked up correctly, leading to the following error:

```
Compilation error in .../packages/core/lib/index.js
Error: extHandler is not a function
    at Object.<anonymous> (.../packages/core/lib/index.js:1:7)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module._compile (.../node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/_k/s4c6xht16s3f1sf2h8xjy2zh0000gn/T/ts-node-dev-hook-4233982185127769.js:93:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at require.extensions..js (/private/var/folders/_k/s4c6xht16s3f1sf2h8xjy2zh0000gn/T/ts-node-dev-hook-4233982185127769.js:96:14)
    at Object.nodeDevHook [as .js] (.../node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
```

When working around this issue by guarding `extHandler`, ES modules seem to make trouble:

```
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Module._compile (.../node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/_k/s4c6xht16s3f1sf2h8xjy2zh0000gn/T/ts-node-dev-hook-7089993507601042.js:58:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at require.extensions.<computed> (/private/var/folders/_k/s4c6xht16s3f1sf2h8xjy2zh0000gn/T/ts-node-dev-hook-7089993507601042.js:60:14)
    at Object.nodeDevHook [as .ts] (.../node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
```

It is worth noting that compiling using `tsc` works fine. I managed to resolve this for me by setting `allowJs: false`, but maybe this is an issue affecting more people 🤔 
Please let me know if I can provide more details!

**Comment by baldore** [comment]
Yes, I'm having the same issue. With `tsc` works fine.

**Comment by whitecolor** [comment]
Will be fixed.

**Comment by whitecolor** [comment]
Should work in latest puplished.

**Comment by fhessenberger** [comment]
thank you! 🎉
