### ISSUE TITLE
Super ugly stack trace

### ISSUE THREAD

**Issue by mcongy** [whitecolor/ts-node-dev#16]
Hello,

I like ts-node-dev very much, but there's a problem that drives me mad.

When there's a typescript error in my code, here's what I see in console:
(This is how I use it: ``` "start": "ts-node-dev --inspect --no-notify -r dotenv/config src/index.ts" ```)

```javascript
Compilation error: { TSError: ⨯ Unable to compile TypeScript
src\index.ts (14,7): Argument of type '5' is not assignable to parameter of type 'string'. (2345)
    at getOutput (C:\Projects\graphql-server-example\node_modules\ts-node-dev\node_modules\ts-node\src\index.ts:330:15)
    at Object.compile (C:\Projects\graphql-server-example\node_modules\ts-node-dev\node_modules\ts-node\src\index.ts:516:11)
    at Object.m._compile (C:\Projects\graphql-server-example\node_modules\ts-node-dev\node_modules\ts-node\src\index.ts:403:43)
    at Object.compile (C:\Projects\graphql-server-example\node_modules\ts-node-dev\lib\compiler.js:156:9)
    at ChildProcess.<anonymous> (C:\Projects\graphql-server-example\node_modules\ts-node-dev\lib\index.js:103:16)
    at ChildProcess.emit (events.js:187:15)
    at emit (internal/child_process.js:807:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  diagnostics:
   [ { message: 'src\\index.ts (14,7): Argument of type \'5\' is not assignable to parameter of type \'string\'. (2345)',
       code: 2345 } ] }
Error: Unable to compile TypeScript
    at Object.<anonymous> (C:\Projects\graphql-server-example\src\index.ts:1:69)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Module.m._compile (C:\Users\congy\AppData\Local\Temp\ts-node-dev-hook-7084678494623908.js:44:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at require.extensions.(anonymous function) (C:\Users\congy\AppData\Local\Temp\ts-node-dev-hook-7084678494623908.js:46:14)
    at Object.nodeDevHook [as .ts] (C:\Projects\graphql-server-example\node_modules\ts-node-dev\lib\hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
[ERROR] 14:38:38 Error: Unable to compile TypeScript
```

Here's what I actually want to see:

```javascript
[ERROR] 14:38:38: TSError: ⨯ Unable to compile TypeScript
src\index.ts (14,7): Argument of type '5' is not assignable to parameter of type 'string'.
```

I have the latest version of typescript, node, ts-node and ts-node-dev.

Is there a way to improve these stacktraces? Or am I doing something wrong?

Thanks

**Comment by whitecolor** [comment]
Yes I will release fixed version soon.

**Comment by whitecolor** [comment]
Check the latest version
