### ISSUE TITLE
Typescript 4.0.2 causes `Cannot read property 'length' of undefined` error

### ISSUE THREAD

**Issue by airhorns** [whitecolor/ts-node-dev#201]
In the process of trying to upgrade a big project using Yarn workspaces to TypeScript 4.0.2, I started getting this error trying to run my API service with `ts-node-dev`. 

```
ts-node-dev ver. 1.0.0-pre.61 (using ts-node ver. 8.10.2, typescript ver. 4.0.2)
Compilation error in /Users/airhorns/Code/gadget/packages/@starscream/core/index.ts
[10:43:57.380 AM] ERROR (root/86965): Cannot read property 'length' of undefined
    Error: Cannot read property 'length' of undefined
        at Object.<anonymous> (/Users/airhorns/Code/gadget/packages/@starscream/core/index.ts:1:7)
        at Module._compile (internal/modules/cjs/loader.js:1256:30)
        at Module._compile (/Users/airhorns/Code/gadget/node_modules/source-map-support/source-map-support.js:547:25)
        at Module.m._compile (/private/var/folders/pr/8710s4wd7cb21yghqtmxzbdr0000gn/T/ts-node-dev-hook-07128352588880538.js:57:33)
        at Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
        at require.extensions..jsx.require.extensions..js (/private/var/folders/pr/8710s4wd7cb21yghqtmxzbdr0000gn/T/ts-node-dev-hook-07128352588880538.js:102:20)
        at require.extensions.<computed> (/private/var/folders/pr/8710s4wd7cb21yghqtmxzbdr0000gn/T/ts-node-dev-hook-07128352588880538.js:59:20)
        at Object.nodeDevHook [as .ts] (/Users/airhorns/Code/gadget/node_modules/ts-node-dev/lib/hook.js:63:13)
        at Module.load (internal/modules/cjs/loader.js:1105:32)
        at Function.Module._load (internal/modules/cjs/loader.js:967:14)
        at Module.require (internal/modules/cjs/loader.js:1145:19)
        at require (internal/modules/cjs/helpers.js:75:18)
        at Object.<anonymous> (/Users/airhorns/Code/gadget/packages/app-sandbox/src/services/ExecuteStateMachine.ts:1:1)
        at Module._compile (internal/modules/cjs/loader.js:1256:30)
        at Module._compile (/Users/airhorns/Code/gadget/node_modules/source-map-support/source-map-support.js:547:25)
        at Module.m._compile (/private/var/folders/pr/8710s4wd7cb21yghqtmxzbdr0000gn/T/ts-node-dev-hook-07128352588880538.js:57:33)
```

The same code works fine when run under `ts-node` on it's own on TypeScript `4.0.2` as well, and the same code compiles and boots just fine under both `ts-node` and `ts-node-dev` on TypeScript `3.9.7`. 

I realize this is not very much information to go on but I'm not exactly sure what steps I can take to try to reveal more about why this is breaking for me just on `ts-node-dev`, so any pointers for gathering more information would be super valuable! Is there any way to get `ts-node-dev` to log or write the source it's trying to evaluate? I tried `tsc`ing my source and I didn't seen anything funky there, and I think if it works under `ts-node` its unlikely that that version of the compiled JS would have the same issue that is affecting `ts-node-dev`.

**Comment by airhorns** [comment]
@whitecolor do you have any tricks for getting ts-node-dev to log the compiled source before evaluating it so I could take a peak at the code that is throwing this error? I apologize for the sparse details and am happy to try to debug myself, it's just hard!

**Comment by whitecolor** [comment]
Yes use `--cache-directory` flag to see compiled sources there, update to the latest version.

**Comment by airhorns** [comment]
Ah, that helps a lot, thanks. I hacked up my local `ts-node-dev` to log the stack of the compiler error, which is the same on TS `4.0.2` and TS `4.0.3`:

```
ts-node-dev ver. 1.0.0-pre.63 (using ts-node ver. 8.10.2, typescript ver. 4.0.2)
Compilation error in /Users/airhorns/Code/gadget/packages/@starscream/core/index.ts TypeError: Cannot read property 'length' of undefined
    at computeLineStarts (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:8840:27)
    at Object.getLineStarts (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:8900:60)
    at getCurrentLineMap (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:98058:59)
    at emitDetachedCommentsAndUpdateCommentsInfo (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:101679:94)
    at emitBodyWithDetachedComments (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:101538:17)
    at emitSourceFile (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:100256:21)
    at pipelineEmitWithHint (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:98139:24)
    at noEmitNotification (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:96697:9)
    at onEmitNode (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:82898:13)
    at onEmitNode (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:93033:17)
```

and this on TS `4.1.0-beta`:

```
ts-node-dev ver. 1.0.0-pre.63 (using ts-node ver. 8.10.2, typescript ver. 4.1.0-beta)
Compilation error in /Users/airhorns/Code/gadget/packages/@starscream/core/index.ts TypeError: Cannot read property 'get' of undefined
    at Object.getJSXImplicitImportBase (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:18760:51)
    at transformSourceFile (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:86737:51)
    at transformSourceFileOrBundle (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:80724:57)
    at transformation (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:98221:24)
    at transformRoot (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:98248:82)
    at Object.transformNodes (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:98232:78)
    at emitJsFileOrBundle (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:98853:32)
    at emitSourceFileOrBundle (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:98800:13)
    at forEachEmittedFile (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:98551:34)
    at Object.emitFiles (/Users/airhorns/Code/gadget/node_modules/typescript/lib/typescript.js:98780:9)
```

That seems like potentially a TS bug and not a `ts-node-dev` bug, but the exact same code boots fine under plain old `ts-node` and typechecks on all the mentioned versions just fine. It also boots under `ts-node-dev` on TS 3.9.8. 

The contents of the file in question were:

```typescript
export { Config } from "./config";
export { connection } from "./database";
export { rootLogger as logger } from "./logger";
export { server } from "./server";
export * from "./types";
export { assert } from "./utils";
```

which seemed super innocuous, but, I realized `export * from "./types";` was ambiguous because I had both a file named `types.ts` and a folder of `.d.ts` files named `types`. When I renamed that folder, the error disappeared 🥳 On both `4.1.0-beta` and `4.0.3`. I imagine there is a bug lurking somewhere deep in TypeScript that only `ts-node-dev` triggers somehow, but it seems very rare and easily avoided. Posting this just incase someone else hits the same issue!

**Comment by whitecolor** [comment]
not sure, there is a flag `--prefer-ts-exts` for cases where corresponding built `js` are near with `ts` sources.
