### ISSUE TITLE
when I run my ts project with unmerged git conflicts I also get this error: Cannot find module '/tmp/ts-node-dev-hook-5528925656195942.js'

### ISSUE THREAD

**Issue by capaj** [whitecolor/ts-node-dev#27]
```
NODE_ENV=development LOOOP_ENVIRONMENT=dev DEBUG=looop*,knex:query,knex:bindings ts-node-dev --transpileOnly src/server.js

tsconfig.json(17,1): error TS1185: Merge conflict marker encountered.

module.js:549
    throw err;
    ^

Error: Cannot find module '/tmp/ts-node-dev-hook-5528925656195942.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at Function.Module._preloadModules (module.js:753:12)
    at preloadModules (bootstrap_node.js:472:38)
    at startup (bootstrap_node.js:185:9)
    at bootstrap_node.js:609:3
```

would be nice if ts-node-dev could handle this edgecase gracefully

**Comment by whitecolor** [comment]
Probably should not work anyway with invalid tsconfig?
