### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined

### ISSUE THREAD

**Issue by gfx** [whitecolor/ts-node-dev#32]
ts-node-dev v1.0.0-pre.28 does not compile my project with the following message:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.fs.openSync (fs.js:572:3)
    at Object.fs.readFileSync (fs.js:485:33)
    at Object.compile (/Users/gfx/.ghq/github.com/bitjourney/kibela/node_modules/ts-node-dev/lib/compiler.js:145:19)
    at ChildProcess.<anonymous> (/Users/gfx/.ghq/github.com/bitjourney/kibela/node_modules/ts-node-dev/lib/index.js:105:16)
    at ChildProcess.emit (events.js:187:15)
    at emit (internal/child_process.js:811:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

This is caused by `fs.readFileSync` and it's here:

https://github.com/whitecolor/ts-node-dev/blob/4dc3e17c369f580bd6be9e8c465ee95b8edc9432/lib/compiler.js#L142-L145

I have injected `console.log("compile prams:", params)` and it shows `compile params: { ready: true }`.

**Comment by whitecolor** [comment]
Check pre.29

**Comment by gfx** [comment]
It looks to be fixed. Thanks.
