### ISSUE TITLE
Can tsconfig.json be made optional?

### ISSUE THREAD

**Issue by kachkaev** [whitecolor/ts-node-dev#36]
I've just started a new Node.js project – all it has is `src/index.ts` and `ts-node` / `typescript` as dev dependencies. Despite that there is no `tsconfig.json`, the following dev command works properly (I assume that some defaults are picked): 

```
  "scripts": {
    "dev": "ts-node src/index.ts"
  },
```

After `yarn add --dev ts-node-dev@1.0.0-pre.30` and replacing `ts-node src/index.ts` with `ts-node-dev --respawn --notify=false src/index.ts`, I'm seeing the following error:

```
/private/var/folders/kz/lrtmrvld16q_q45z8pg1dsskrbyg3_l/T/ts-node-dev-hook-42574828773943385.js:99
      throw new Error('Waiting ts-node-dev ready file failed')
      ^

Error: Waiting ts-node-dev ready file failed
    at Object.<anonymous> (/private/var/folders/kz/lrtmrvld16q_q45z8pg1dsskrbyg3_l/T/ts-node-dev-hook-42574828773943385.js:99:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:805:12)
    at preloadModules (internal/bootstrap/node.js:588:7)
    at startup (internal/bootstrap/node.js:269:9)
```

Creating `tsconfig.json` with an empty object resolves the issue. However, given that in my case this new file does not carry any payload and `ts-node` works without it, can it be made optional for ts-node-dev as well?

**Comment by whitecolor** [comment]
Ok, will remove the check in the next update.
