### ISSUE TITLE
Stack trace shows wrong line number

### ISSUE THREAD

**Issue by gaelduplessix** [whitecolor/ts-node-dev#44]
It looks like stack traces don't report the correct line number.
Reproduction steps:

- Create a file `index.ts` as:

```ts


/**
 * Some
 * long
 * comments
 * to offset sources
 */


 
throw new Error();
```

- With stock typescript config (no `tsconfig.json`), run `ts-node-dev index.ts`
- The output is:
```
Using ts-node version 7.0.1, typescript version 3.2.2
Error
    at Object.<anonymous> (/Users/gael/dev/index.ts:7:7)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Module.m._compile (/private/var/folders/_9/37c42sdn1c31kmk9mcp0z9qc0000gn/T/ts-node-dev-hook-9368575770193885.js:55:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at require.extensions.(anonymous function) (/private/var/folders/_9/37c42sdn1c31kmk9mcp0z9qc0000gn/T/ts-node-dev-hook-9368575770193885.js:57:14)
    at Object.nodeDevHook [as .ts] (/Users/gael/dev/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
[ERROR] 14:47:11 Error
```

The error is reported on line `7` instead of line `12`. This is a rather simple example but the offset is even bigger in larger files.

I assume this is somehow related to source maps. I would gladly try to open a PR to fix that bug if you can give me any insights on what could be the problem here.

Thanks

**Comment by whitecolor** [comment]
Try to use with https://github.com/evanw/node-source-map-support

**Comment by gaelduplessix** [comment]
Indeed, that fixed my problem. Thx :)

Shouldn't this be mentioned in the docs though? Or included by default?

**Comment by nchaulet** [comment]
@gaelduplessix Hi I am having issue with source map did you put any options when using `source-map-support`?

Thanks for the help.

**Comment by malthe** [comment]
> Probably will add in docs about it.

Please do.

**Comment by basarat** [comment]
^ I would recommend that code (https://github.com/whitecolor/ts-node-dev/issues/44#issuecomment-452404543) going into `ts-node-dev` e.g. ts-node sets up `source-map-support` based on its use case : https://github.com/TypeStrong/ts-node/blob/d58488b810ba06291f6267fdf020c354cf3f4ce5/src/index.ts#L186 :rose:

**Comment by bard** [comment]
The above doesn't work for me, still investigating. I have to wonder though, why would it be needed if ts-node is already setting up `source-map-support`?

**Comment by LunarLanding** [comment]
I have the same issue. I have created [a repo](https://github.com/LunarLanding/ts-node-dev-line-error) with a minimal failing test. The second commit attempts to use source-map-support, to no avail.

**Comment by whitecolor** [comment]
Hey, should be working now, added support for this.
