### ISSUE TITLE
EMFILE: too many open files, watch

### ISSUE THREAD

**Issue by ccorcos** [whitecolor/ts-node-dev#63]
My server crashes when I tried replacing nodemon with this package.

```
Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
Error: Unexpected exit status for 'node_modules/.bin/ts-node-dev  --project tsconfig.server.json src/tools/runServer.ts --fast --minifiy --offline --verbose': got 1, expected 0
    at ChildProcess.<anonymous> (/Users/chet/Code/notion-next/src/cli/utils.ts:334:6)
    at ChildProcess.emit (events.js:197:13)
    at ChildProcess.EventEmitter.emit (domain.js:446:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

**Comment by whitecolor** [comment]
@ccorcos does your launched code contains many files, note that ts-node-dev watches only required files by the process, not all the files in the folder.

**Comment by ccorcos** [comment]
Yeah, its a pretty big project... Approximately 427 source files (not including `node_modules` which should get ignored).

**Comment by Brokray** [comment]
Exact same problem here if I run with `--inspect=xxxx`.
If I don't set the option it just falls in an infinite loop.

**Comment by whitecolor** [comment]
Will see if it happens with chokidar.

**Comment by diegocrivelaro** [comment]
I have the same problem

```bash
[INFO] 22:15:04 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.8.3)
Error: EMFILE: too many open files, watch '/tmp/.ts-nodeJbZlkm/compiled/4532292325084202.req'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2264:34)
    at createFsWatchInstance (/home/diegocrivelaro/Projects/Studies/NLW_eSports/server/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/diegocrivelaro/Projects/Studies/NLW_eSports/server/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/diegocrivelaro/Projects/Studies/NLW_eSports/server/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/diegocrivelaro/Projects/Studies/NLW_eSports/server/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/diegocrivelaro/Projects/Studies/NLW_eSports/server/node_modules/chokidar/lib/nodefs-handler.js:637:21)
    at async /home/diegocrivelaro/Projects/Studies/NLW_eSports/server/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  path: '/tmp/.ts-nodeJbZlkm/compiled/4532292325084202.req',
  filename: '/tmp/.ts-nodeJbZlkm/compiled/4532292325084202.req'
}
```
