### ISSUE TITLE
ts-node -O (--compilerOptions) failing

### ISSUE THREAD

**Issue by markfknight** [whitecolor/ts-node-dev#7]
Hi, 

I have been playing with ts-node-dev with a project using ES2016 modules. To get round my TypeScript output ES2016 modules not working in node I have been trying to run ts-node-dev in my package.json as follows 

`ts-node-dev -O '{\ "module\": \"commonjs\" }' --respawn ./src/index.ts`

I am getting the following error:  

```
{ TSError: ⨯ Unable to compile TypeScript
Unknown compiler option '0'. (5023)
Unknown compiler option '1'. (5023)
Unknown compiler option '2'. (5023)
Unknown compiler option '3'. (5023)
Unknown compiler option '4'. (5023)
Unknown compiler option '5'. (5023)
Unknown compiler option '6'. (5023)
Unknown compiler option '7'. (5023)
Unknown compiler option '8'. (5023)
Unknown compiler option '9'. (5023)
Unknown compiler option '10'. (5023)
Unknown compiler option '11'. (5023)
Unknown compiler option '12'. (5023)
Unknown compiler option '13'. (5023)
Unknown compiler option '14'. (5023)
Unknown compiler option '15'. (5023)
Unknown compiler option '16'. (5023)
Unknown compiler option '17'. (5023)
Unknown compiler option '18'. (5023)
Unknown compiler option '19'. (5023)
Unknown compiler option '20'. (5023)
Unknown compiler option '21'. (5023)
Unknown compiler option '22'. (5023)
Unknown compiler option '23'. (5023)
    at register (/Users/markfknight/Documents/Projects/vue-rx-property-decorator/node_modules/ts-node/src/index.ts:220:11)
    at Object.init (/Users/markfknight/Documents/Projects/vue-rx-property-decorator/node_modules/ts-node-dev/lib/compiler.js:97:7)
    at module.exports (/Users/markfknight/Documents/Projects/vue-rx-property-decorator/node_modules/ts-node-dev/lib/index.js:9:12)
    at Object.<anonymous> (/Users/markfknight/Documents/Projects/vue-rx-property-decorator/node_modules/ts-node-dev/bin/ts-node-dev:60:1)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
  diagnostics:
   [ { message: 'Unknown compiler option \'0\'. (5023)', code: 5023 },
     { message: 'Unknown compiler option \'1\'. (5023)', code: 5023 },
     { message: 'Unknown compiler option \'2\'. (5023)', code: 5023 },
     { message: 'Unknown compiler option \'3\'. (5023)', code: 5023 },
     { message: 'Unknown compiler option \'4\'. (5023)', code: 5023 },
     { message: 'Unknown compiler option \'5\'. (5023)', code: 5023 },
     { message: 'Unknown compiler option \'6\'. (5023)', code: 5023 },
     { message: 'Unknown compiler option \'7\'. (5023)', code: 5023 },
     { message: 'Unknown compiler option \'8\'. (5023)', code: 5023 },
     { message: 'Unknown compiler option \'9\'. (5023)', code: 5023 },
     { message: 'Unknown compiler option \'10\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'11\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'12\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'13\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'14\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'15\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'16\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'17\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'18\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'19\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'20\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'21\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'22\'. (5023)',
       code: 5023 },
     { message: 'Unknown compiler option \'23\'. (5023)',
       code: 5023 } ] }
module.js:559
    throw err;
    ^

Error: Cannot find module '/var/folders/xf/j5rpxz_51lzc5bz8trk2194r0000gn/T/ts-node-dev-hook-1520191060655.js'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at Function.Module._preloadModules (module.js:763:12)
    at preloadModules (bootstrap_node.js:526:38)
    at startup (bootstrap_node.js:190:9)
    at bootstrap_node.js:660:3
```

Hitting ts-node directly with the -O flag does not through the error.

OSX: 10.13.3
Node: v9.7.1
TypeScript: 2.7.2
ts-node-dev: 1.0.0-pre.17

**Comment by whitecolor** [comment]
Thanks, should be fixed in published version.

**Comment by markfknight** [comment]
Awesome, working as expected. Many thanks!
